fix: use disjoint set for coop scheduling

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,10 +28,17 @@ jobs:
       - name: Evaluate definitions
         id: definitions
         run: |
-          export MSRV=$(rustup show | awk 'NF' | awk 'END{print $2}')
+          rustup show active-toolchain
+          export MSRV=$(rustup show active-toolchain | awk -F'-' '{print $1}')
+          echo "msrv=$MSRV"
+          if [ -z "$MSRV" ]; then
+            echo "Error: MSRV did not parse correctly"
+            exit 1
+          fi
           echo "msrv=$MSRV" >> "$GITHUB_OUTPUT"
-          export RAW_VERSIONS="stable $RUST_NIGHTLY_TOOLCHAIN $MSRV"
+          export RAW_VERSIONS="stable $MSRV"
           export VERSIONS=$(echo $RAW_VERSIONS | jq -scR 'rtrimstr("\n")|split(" ")|.')
+          echo "$VERSIONS"
           echo "versions=$VERSIONS" >> "$GITHUB_OUTPUT"
 
   rustfmt:
@@ -92,14 +99,15 @@ jobs:
     runs-on: ${{ matrix.os }}
     needs: env
     strategy:
+      fail-fast: false
       matrix:
         rust: ${{ fromJson(needs.env.outputs.rust-versions) }}
         os: [ubuntu-latest, macOS-latest, windows-latest]
-        features: [default]
+        features: ["default", ""]
         include:
           - rust: stable
             os: ubuntu-latest
-            features: tracing,metrics
+            features: default,metrics
     steps:
       - uses: actions/checkout@v4
         with:
@@ -116,8 +124,11 @@ jobs:
           key: ${{ matrix.target }}
 
       - name: Run tests
+        env:
+          DEFAULT_FEATURES: ${{ contains(matrix.features, 'default') && '' || ' --no-default-features' }}
+          FEATURES_LIST: ${{ matrix.features && format(' --features {0}', matrix.features) || '' }}
         run: |
-          cargo test ${{ matrix.features != 'default' && '--features' || '' }} ${{ matrix.features }}
+          cargo test $DEFAULT_FEATURES $FEATURES_LIST
 
   miri:
     runs-on: ubuntu-latest
